Refactor tests and allow searching with new type
kbaseapps/GenomeSearchUtil pull request #3
Opened 2017-12-21 19:49 UTC by JamesJeffryes

The code with now also index features in the mrnas, cdss and non_codeing_features arrays as well as deal with braking changes to the alias, function and ontology fields. This PR updates the tests to use local genomes of old an new types.

2018-01-02 19:22 UTC, JamesJeffryes commented
@briehl Thanks for the review

2018-01-05 01:47 UTC, briehl commented on GenomeSearchUtil.spec
> +            it's array in a Genome object,
it's -> its (yeah, I know I'm being pedantic...)

2018-01-05 02:07 UTC, briehl requested changes
Looks pretty good, some minor tweaks to names.
However, tests are failing, since the GenomeSearchUtil_server_test module can't find the AssemblyUtil. Maybe it didn't get added in your commit?

2018-01-05 02:07 UTC, briehl commented on kbase.yml
> +    [scannon, sychan, jjeffryes]
scannon -> scanon

2018-01-05 02:07 UTC, briehl commented on GenomeSearchUtil.spec
> +            it's array in a Genome object,
Also, is there a list of allowed names? If not, all of those (not just a sample) should be here.

2018-01-05 02:07 UTC, briehl commented on lib/GenomeSearchUtil/GenomeSearchUtilIndexer.py
> +                 'non_codeing_features/[*]/'],
non_codeing_features -> non_coding_features (I think, that's what's used above, at least)

2018-01-05 11:54 UTC, JamesJeffryes commented
@briehl @sychan I've addressed Bill's comments and added the Assembly Utils dependancy. If the tests run can you merge & register the app?

2018-01-05 20:06 UTC, briehl approved these changes

2018-01-05 20:06 UTC, merged